name: networkcalculator
description: Calculate easily IPv4 and IPv6 Subnets!

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.2+5

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: 6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true